M48
; DRILL file {KiCad 7.0.8} date 2025 January 24, Friday 11:11:37
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-01-24T11:11:37-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X151.13Y-49.65
X162.56Y-49.65
X171.0Y-49.65
X182.43Y-49.65
T0
M30
